---

- name: "Additional - Ensure dest template dir exists"
  become: yes
  become_user: "{{ deploy_app_user }}"
  file:
    path: "{{ item.dest | dirname }}"
    state: directory
  with_items: "{{ deploy_additional_templates }}"

- name: "Additional - Ensure dest copy dir exists"
  become: yes
  become_user: "{{ deploy_app_user }}"
  file:
    path: "{{ item.dest | dirname }}"
    state: directory
  with_items: "{{ deploy_additional_copy }}"

- name: "Additional - Deploy templates"
  become: yes
  become_user: "{{ deploy_app_user }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.user | default(deploy_app_user) }}"
    group: "{{ item.group | default(deploy_app_group) }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items: "{{ deploy_additional_templates }}"

- name: "Additional - Deploy copy files"
  become: yes
  become_user: "{{ deploy_app_user }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.user | default(deploy_app_user) }}"
    group: "{{ item.group | default(deploy_app_group) }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items: "{{ deploy_additional_copy }}"

- name: "Additional - Create directories"
  become: yes
  become_user: "{{ deploy_app_user }}"
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.user | default(deploy_app_user) }}"
    group: "{{ item.group | default(deploy_app_group) }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items: "{{ create_additional_dir }}"